-- ════════════════════════════════════════════════════════════════════════
-- Bookly MY — Inventory 升级 SQL
-- 在 Supabase Dashboard → SQL Editor 里整段粘贴运行（可重复运行，幂等）
-- ════════════════════════════════════════════════════════════════════════

-- 1) inventory 表：补充 user_id 和 image_url 字段
alter table public.inventory add column if not exists user_id uuid default auth.uid();
alter table public.inventory add column if not exists image_url text;

-- 给历史数据补 user_id（把现有无主数据归到第一个注册用户；如果你是唯一用户这就是你）
update public.inventory set user_id = (select id from auth.users order by created_at limit 1)
where user_id is null;

-- 2) 库存历史记录表
create table if not exists public.stock_movements (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default auth.uid(),
  item_id     bigint not null references public.inventory(id) on delete cascade,
  type        text not null check (type in ('purchase','sale','return','damaged','adjust')),
  qty_change  numeric not null,
  qty_before  numeric not null default 0,
  qty_after   numeric not null default 0,
  note        text,
  invoice_no  text,
  created_at  timestamptz not null default now()
);
create index if not exists idx_movements_item on public.stock_movements(item_id, created_at desc);
create index if not exists idx_movements_user on public.stock_movements(user_id, created_at desc);

-- 3) RLS：两张表都只允许本人读写
alter table public.inventory       enable row level security;
alter table public.stock_movements enable row level security;

drop policy if exists "inventory_own" on public.inventory;
create policy "inventory_own" on public.inventory
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- 历史记录不允许从客户端修改/删除（审计完整性），只允许 insert 和 select
drop policy if exists "movements_own"    on public.stock_movements;
drop policy if exists "movements_select" on public.stock_movements;
drop policy if exists "movements_insert" on public.stock_movements;
create policy "movements_select" on public.stock_movements
  for select using (user_id = auth.uid());
create policy "movements_insert" on public.stock_movements
  for insert with check (user_id = auth.uid());

-- 4) 产品图片存储桶（公开读取，本人可写）
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

drop policy if exists "product_images_read"   on storage.objects;
drop policy if exists "product_images_insert" on storage.objects;
drop policy if exists "product_images_delete" on storage.objects;

create policy "product_images_read" on storage.objects
  for select using (bucket_id = 'product-images');

create policy "product_images_insert" on storage.objects
  for insert with check (
    bucket_id = 'product-images'
    and auth.uid() is not null
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "product_images_delete" on storage.objects
  for delete using (
    bucket_id = 'product-images'
    and (storage.foldername(name))[1] = auth.uid()::text
  );
