-- ══════════════════════════════════════════════════════════════════════════
-- Bookly MY — Supabase 完整建库脚本（新项目 dgquwkdzmufnrnwquvci 专用）
-- 在 Supabase Dashboard → SQL Editor 整段粘贴运行
-- 幂等设计：可以重复运行，不会破坏已有数据
-- ══════════════════════════════════════════════════════════════════════════

-- ─── 1. 交易表（收入/支出/SST） ─────────────────────────────────────────────
create table if not exists public.transactions (
  id            bigint not null,
  user_id       uuid   not null default auth.uid(),
  type          text,
  cat_id        text,
  amount_myr    numeric,
  orig_amount   numeric,
  orig_currency text,
  sst_key       text,
  sst_myr       numeric,
  desc_en       text,
  desc_zh       text,
  date          text,
  entries       text,
  primary key (id, user_id)          -- 对应代码里 onConflict: 'id,user_id'
);
create index if not exists idx_tx_user_date on public.transactions(user_id, date desc);

-- ─── 2. 客户表 ──────────────────────────────────────────────────────────────
create table if not exists public.customers (
  id         bigint not null,
  user_id    uuid   not null default auth.uid(),
  name       text,
  reg_no     text,
  sst_reg_no text,
  address    text,
  phone      text,
  email      text,
  primary key (id, user_id)
);

-- ─── 3. 员工表（薪资/EPF/SOCSO） ────────────────────────────────────────────
create table if not exists public.employees (
  id           bigint not null,
  user_id      uuid   not null default auth.uid(),
  name         text,
  ic_no        text,
  position     text,
  department   text,
  basic_salary numeric,
  epf_no       text,
  socso_no     text,
  bank_name    text,
  bank_acct    text,
  phone        text,
  email        text,
  primary key (id, user_id)
);

-- ─── 4. 发票流水号（每年一行） ──────────────────────────────────────────────
create table if not exists public.invoice_seq (
  user_id  uuid    not null default auth.uid(),
  year     integer not null,
  last_seq integer not null default 0,
  primary key (user_id, year)        -- 对应 onConflict: 'user_id,year'
);

-- ─── 5. 用户设置（JSON 整包同步） ───────────────────────────────────────────
create table if not exists public.user_settings (
  user_id    uuid primary key default auth.uid(),
  settings   jsonb,
  updated_at timestamptz default now()
);

-- ─── 6. 发票/薪资单数据（JSON 整包同步） ────────────────────────────────────
create table if not exists public.user_data (
  user_id    uuid primary key default auth.uid(),
  invoices   jsonb,
  payrolls   jsonb,
  updated_at timestamptz default now()
);

-- ─── 7. 库存产品表 ──────────────────────────────────────────────────────────
create table if not exists public.inventory (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null default auth.uid(),
  name         text not null,
  sku          text default '',
  unit         text default 'pcs',
  cost_price   numeric default 0,
  sell_price   numeric default 0,
  qty          numeric default 0,
  low_stock_at numeric default 5,
  category     text,
  notes        text,
  image_url    text,
  created_at   timestamptz default now(),
  updated_at   timestamptz default now()
);
create index if not exists idx_inventory_user on public.inventory(user_id, name);

-- ─── 8. 库存历史记录表（审计，不可改不可删） ────────────────────────────────
create table if not exists public.stock_movements (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default auth.uid(),
  item_id     bigint not null references public.inventory(id) on delete cascade,
  type        text not null check (type in ('purchase','sale','return','damaged','adjust')),
  qty_change  numeric not null,
  qty_before  numeric not null default 0,
  qty_after   numeric not null default 0,
  note        text,
  invoice_no  text,
  created_at  timestamptz not null default now()
);
create index if not exists idx_movements_item on public.stock_movements(item_id, created_at desc);
create index if not exists idx_movements_user on public.stock_movements(user_id, created_at desc);

-- ══════════════════════════════════════════════════════════════════════════
-- RLS 权限策略：每个用户只能读写自己的数据（防止 anon key 被滥用的关键防线）
-- ══════════════════════════════════════════════════════════════════════════
alter table public.transactions    enable row level security;
alter table public.customers       enable row level security;
alter table public.employees       enable row level security;
alter table public.invoice_seq     enable row level security;
alter table public.user_settings   enable row level security;
alter table public.user_data       enable row level security;
alter table public.inventory       enable row level security;
alter table public.stock_movements enable row level security;

do $$
declare t text;
begin
  foreach t in array array['transactions','customers','employees','invoice_seq',
                           'user_settings','user_data','inventory']
  loop
    execute format('drop policy if exists "%s_own" on public.%I', t, t);
    execute format(
      'create policy "%s_own" on public.%I for all using (user_id = auth.uid()) with check (user_id = auth.uid())',
      t, t);
  end loop;
end $$;

-- 历史记录只允许 查询+插入（禁止客户端篡改/删除，保证审计完整性）
drop policy if exists "movements_select" on public.stock_movements;
drop policy if exists "movements_insert" on public.stock_movements;
create policy "movements_select" on public.stock_movements
  for select using (user_id = auth.uid());
create policy "movements_insert" on public.stock_movements
  for insert with check (user_id = auth.uid());

-- ══════════════════════════════════════════════════════════════════════════
-- 产品图片存储桶（公开读取，本人可上传/删除）
-- ══════════════════════════════════════════════════════════════════════════
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

drop policy if exists "product_images_read"   on storage.objects;
drop policy if exists "product_images_insert" on storage.objects;
drop policy if exists "product_images_delete" on storage.objects;

create policy "product_images_read" on storage.objects
  for select using (bucket_id = 'product-images');

create policy "product_images_insert" on storage.objects
  for insert with check (
    bucket_id = 'product-images'
    and auth.uid() is not null
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "product_images_delete" on storage.objects
  for delete using (
    bucket_id = 'product-images'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- ══════════════════════════════════════════════════════════════════════════
-- 完成！运行成功后应显示 "Success. No rows returned"
-- ══════════════════════════════════════════════════════════════════════════
