// ─── delivery_order_pdf.dart ──────────────────────────────────────────────────
// Malaysia Delivery Order — quantities only (no prices), with received-by sign-off
// ─────────────────────────────────────────────────────────────────────────────

import 'dart:convert';
import 'dart:typed_data';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../models.dart';

const _black  = PdfColors.black;
const _grey   = PdfColor.fromInt(0xFF555555);
const _light  = PdfColor.fromInt(0xFF888888);
const _rule   = PdfColor.fromInt(0xFFBBBBBB);
const _rowAlt = PdfColor.fromInt(0xFFF7F7F7);

Future<Uint8List> generateDeliveryOrderPdf({
  required AppSettings co,
  required Customer    customer,
  required List<Map<String, String>> rows,
  required String doNo,
  required String doDate,
  String? refInvNo,
  String? logoBase64,
  String? notes,
}) async {

  pw.Font? cjk;
  pw.Font? cjkBold;
  try {
    final fd = await rootBundle.load('assets/fonts/NotoSansSC-Regular.ttf');
    cjk = pw.Font.ttf(fd);
  } catch (_) {}
  try {
    final fd = await rootBundle.load('assets/fonts/NotoSansSC-Bold.ttf');
    cjkBold = pw.Font.ttf(fd);
  } catch (_) { cjkBold = cjk; }

  final List<pw.Font> fb = cjk != null ? [cjk] : [];
  final pw.ThemeData theme = cjk != null
      ? pw.ThemeData.withFont(base: cjk, bold: cjkBold ?? cjk)
      : pw.ThemeData();

  pw.TextStyle ts(double sz, {PdfColor? c, bool bold = false}) => pw.TextStyle(
      fontSize: sz,
      color: c ?? _black,
      fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
      fontFallback: fb);

  pw.MemoryImage? logo;
  if (logoBase64 != null && logoBase64.isNotEmpty) {
    try { logo = pw.MemoryImage(base64Decode(logoBase64.split(',').last)); } catch (_) {}
  }

  final totalQty = rows.fold<double>(0, (s, r) => s + (double.tryParse(r['qty'] ?? '0') ?? 0));

  pw.Widget rule({double thick = 0.5, PdfColor? color}) =>
      pw.Divider(thickness: thick, color: color ?? _rule, height: 1);
  pw.Widget gap(double h) => pw.SizedBox(height: h);

  pw.Widget metaRow(String label, String value,
      pw.TextStyle labelStyle, pw.TextStyle valueStyle) =>
    pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 2),
      child: pw.Row(mainAxisAlignment: pw.MainAxisAlignment.end, children: [
        pw.Text('$label:  ', style: labelStyle),
        pw.Text(value, style: valueStyle),
      ]),
    );

  final pdf = pw.Document(theme: theme);

  pdf.addPage(pw.MultiPage(
    pageFormat: PdfPageFormat.a4,
    margin: const pw.EdgeInsets.fromLTRB(52, 48, 52, 40),
    footer: (ctx) => pw.Container(
      padding: const pw.EdgeInsets.only(top: 6),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text('Generated by Bookly MY  ·  $doDate', style: ts(7, c: _light)),
          pw.Text('Page ${ctx.pageNumber} of ${ctx.pagesCount}', style: ts(7, c: _light)),
        ],
      ),
    ),
    build: (ctx) => [

      // ══ HEADER ══════════════════════════════════════════════════════════
      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                if (logo != null) ...[
                  pw.Image(logo, height: 44, fit: pw.BoxFit.contain),
                  gap(6),
                ],
                pw.Text(co.companyName, style: ts(11, bold: true)),
                if (co.coReg.isNotEmpty)
                  pw.Text('SSM/Reg No: ${co.coReg}',    style: ts(8, c: _grey)),
                if (co.coAddr.isNotEmpty)
                  pw.Text(co.coAddr,                    style: ts(8, c: _grey)),
                if (co.coPhone.isNotEmpty)
                  pw.Text('Tel: ${co.coPhone}',         style: ts(8, c: _grey)),
                if (co.coEmail.isNotEmpty)
                  pw.Text(co.coEmail,                   style: ts(8, c: _grey)),
              ],
            ),
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text('DELIVERY ORDER', style: ts(20, bold: true)),
              gap(10),
              metaRow('D.O. No', doNo,   ts(8, c: _grey), ts(8, bold: true)),
              metaRow('Date',    doDate, ts(8, c: _grey), ts(8)),
              if (refInvNo != null && refInvNo.isNotEmpty)
                metaRow('Ref. Invoice', refInvNo, ts(8, c: _grey), ts(8)),
            ],
          ),
        ],
      ),

      gap(20),
      rule(thick: 1.0, color: _black),
      gap(14),

      // ══ DELIVER TO ════════════════════════════════════════════════════════
      pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('DELIVER TO', style: ts(7, c: _light, bold: true)),
          gap(4),
          pw.Text(customer.name, style: ts(10, bold: true)),
          if (customer.regNo.isNotEmpty)
            pw.Text('SSM/Reg No: ${customer.regNo}', style: ts(8, c: _grey)),
          if (customer.address.isNotEmpty)
            pw.Text(customer.address,                style: ts(8, c: _grey)),
          if (customer.phone.isNotEmpty)
            pw.Text(customer.phone,                  style: ts(8, c: _grey)),
        ],
      ),

      gap(18),
      rule(thick: 1.0, color: _black),

      // ══ TABLE HEADER (NO PRICES) ══════════════════════════════════════════
      pw.Padding(
        padding: const pw.EdgeInsets.symmetric(vertical: 6),
        child: pw.Row(children: [
          pw.SizedBox(width: 24,
              child: pw.Text('NO',          style: ts(7.5, c: _grey, bold: true))),
          pw.Expanded(
              child: pw.Text('DESCRIPTION', style: ts(7.5, c: _grey, bold: true))),
          pw.SizedBox(width: 70,
              child: pw.Text('QUANTITY',    style: ts(7.5, c: _grey, bold: true),
                  textAlign: pw.TextAlign.right)),
        ]),
      ),
      rule(),

      // ══ TABLE ROWS ════════════════════════════════════════════════════════
      ...rows.asMap().entries.map((entry) {
        final i = entry.key;
        final r = entry.value;
        final qty = double.tryParse(r['qty'] ?? '0') ?? 0;
        return pw.Container(
          color: i.isOdd ? _rowAlt : null,
          padding: const pw.EdgeInsets.symmetric(vertical: 6),
          child: pw.Row(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
            pw.SizedBox(width: 24,
                child: pw.Text('${i + 1}', style: ts(8, c: _grey))),
            pw.Expanded(child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
              pw.Text(r['desc'] ?? '', style: ts(8.5)),
              if ((r['note'] ?? '').isNotEmpty)
                pw.Text(r['note']!, style: ts(7, c: _grey)),
            ])),
            pw.SizedBox(width: 70,
                child: pw.Text(qty.toStringAsFixed(qty == qty.truncate() ? 0 : 2),
                    style: ts(9, bold: true), textAlign: pw.TextAlign.right)),
          ]),
        );
      }),

      rule(),
      gap(6),
      pw.Row(mainAxisAlignment: pw.MainAxisAlignment.end, children: [
        pw.Text('Total Quantity:  ', style: ts(9, c: _grey, bold: true)),
        pw.Text(totalQty.toStringAsFixed(totalQty == totalQty.truncate() ? 0 : 2),
            style: ts(10, bold: true)),
      ]),

      // ══ NOTES ════════════════════════════════════════════════════════════
      if (notes != null && notes.isNotEmpty) ...[
        gap(16),
        rule(),
        gap(8),
        pw.Text('Notes', style: ts(8, c: _grey, bold: true)),
        gap(4),
        pw.Text(notes, style: ts(8.5, c: _grey)),
      ],

      // ══ SIGN-OFF (received by) ════════════════════════════════════════════
      gap(40),
      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.end,
        children: [
          pw.Expanded(child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
            pw.Container(width: 160, height: 0.8, color: _black),
            gap(4),
            pw.Text('Issued By / Authorised Signature', style: ts(7.5, c: _grey)),
            pw.Text(co.companyName, style: ts(8, bold: true)),
          ])),
          pw.SizedBox(width: 40),
          pw.Expanded(child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
            pw.Container(width: 160, height: 0.8, color: _black),
            gap(4),
            pw.Text('Received By (Name & Date)', style: ts(7.5, c: _grey)),
            pw.Text('Goods received in good order & condition',
                style: ts(7, c: _light)),
          ])),
        ],
      ),
    ],
  ));

  return pdf.save();
}
