// ─── payroll_report_pdf.dart ──────────────────────────────────────────────────
// Generic tabular report PDF used by CP39, EPF/SOCSO/EIS, and EA reports.
// ─────────────────────────────────────────────────────────────────────────────

import 'dart:typed_data';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../models.dart';

const _black = PdfColors.black;
const _grey  = PdfColor.fromInt(0xFF555555);
const _light = PdfColor.fromInt(0xFF888888);
const _rule  = PdfColor.fromInt(0xFFBBBBBB);
const _alt   = PdfColor.fromInt(0xFFF7F7F7);
const _head  = PdfColor.fromInt(0xFFEDEDED);

/// Builds a company-header report with a single data table.
/// [aligns] (per column) defaults to left; pass TextAlign.right for numbers.
Future<Uint8List> generateTableReportPdf({
  required AppSettings co,
  required String title,
  String? subtitle,
  required List<String> headers,
  required List<List<String>> rows,
  List<String>? totals,
  List<bool>? rightCols,
  List<int>? flex,
  String? note,
}) async {
  pw.Font? cjk;
  pw.Font? cjkBold;
  try { cjk = pw.Font.ttf(await rootBundle.load('assets/fonts/NotoSansSC-Regular.ttf')); } catch (_) {}
  try { cjkBold = pw.Font.ttf(await rootBundle.load('assets/fonts/NotoSansSC-Bold.ttf')); } catch (_) { cjkBold = cjk; }
  final fb = cjk != null ? [cjk] : <pw.Font>[];
  final theme = cjk != null ? pw.ThemeData.withFont(base: cjk, bold: cjkBold ?? cjk) : pw.ThemeData();

  pw.TextStyle ts(double s, {PdfColor? c, bool bold = false}) => pw.TextStyle(
      fontSize: s, color: c ?? _black,
      fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal, fontFallback: fb);

  final cols = headers.length;
  final colFlex   = flex ?? List<int>.filled(cols, 1);
  final colAligns = List<pw.TextAlign>.generate(cols, (i) =>
      (rightCols != null && i < rightCols.length && rightCols[i])
          ? pw.TextAlign.right : pw.TextAlign.left);

  pw.Widget cell(String text, pw.TextStyle style, pw.TextAlign a) =>
      pw.Text(text, style: style, textAlign: a);

  pw.TableRow rowOf(List<String> cells, pw.TextStyle style, {PdfColor? bg}) =>
      pw.TableRow(
        decoration: bg != null ? pw.BoxDecoration(color: bg) : null,
        children: List.generate(cols, (i) => pw.Padding(
          padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 5),
          child: cell(i < cells.length ? cells[i] : '', style, colAligns[i]),
        )),
      );

  final pdf = pw.Document(theme: theme);
  pdf.addPage(pw.MultiPage(
    pageFormat: PdfPageFormat.a4,
    margin: const pw.EdgeInsets.fromLTRB(40, 44, 40, 40),
    footer: (ctx) => pw.Padding(
      padding: const pw.EdgeInsets.only(top: 6),
      child: pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, children: [
        pw.Text('Generated by Bookly MY', style: ts(7, c: _light)),
        pw.Text('Page ${ctx.pageNumber} of ${ctx.pagesCount}', style: ts(7, c: _light)),
      ]),
    ),
    build: (ctx) => [
      // Header
      pw.Text(co.companyName, style: ts(13, bold: true)),
      if (co.coReg.isNotEmpty) pw.Text('SSM/Reg No: ${co.coReg}', style: ts(8, c: _grey)),
      if (co.coAddr.isNotEmpty) pw.Text(co.coAddr, style: ts(8, c: _grey)),
      pw.SizedBox(height: 12),
      pw.Text(title, style: ts(16, bold: true)),
      if (subtitle != null && subtitle.isNotEmpty)
        pw.Text(subtitle, style: ts(9, c: _grey)),
      pw.SizedBox(height: 10),
      pw.Divider(thickness: 1, color: _black, height: 1),
      pw.SizedBox(height: 8),

      // Table
      pw.Table(
        columnWidths: {
          for (var i = 0; i < cols; i++) i: pw.FlexColumnWidth(colFlex[i].toDouble()),
        },
        border: pw.TableBorder(
          horizontalInside: pw.BorderSide(color: _rule, width: 0.5),
          bottom: pw.BorderSide(color: _rule, width: 0.5),
        ),
        children: [
          rowOf(headers, ts(8, c: _grey, bold: true), bg: _head),
          ...rows.asMap().entries.map((e) =>
              rowOf(e.value, ts(8.5), bg: e.key.isOdd ? _alt : null)),
          if (totals != null) rowOf(totals, ts(9, bold: true), bg: _head),
        ],
      ),

      if (note != null && note.isNotEmpty) ...[
        pw.SizedBox(height: 14),
        pw.Text(note, style: ts(7.5, c: _light)),
      ],
    ],
  ));
  return pdf.save();
}
