// ─── purchase_order_pdf.dart ──────────────────────────────────────────────────
// Purchase Order — issued by us to a supplier (shows prices + total).
// ─────────────────────────────────────────────────────────────────────────────

import 'dart:convert';
import 'dart:typed_data';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../models.dart';

const _black = PdfColors.black;
const _grey  = PdfColor.fromInt(0xFF555555);
const _light = PdfColor.fromInt(0xFF888888);
const _rule  = PdfColor.fromInt(0xFFBBBBBB);
const _alt   = PdfColor.fromInt(0xFFF7F7F7);

Future<Uint8List> generatePurchaseOrderPdf({
  required AppSettings co,
  required Map<String, dynamic> supplier,
  required List<Map<String, String>> rows,
  required String poNo,
  required String poDate,
  String? logoBase64,
  String? notes,
}) async {
  pw.Font? cjk; pw.Font? cjkBold;
  try { cjk = pw.Font.ttf(await rootBundle.load('assets/fonts/NotoSansSC-Regular.ttf')); } catch (_) {}
  try { cjkBold = pw.Font.ttf(await rootBundle.load('assets/fonts/NotoSansSC-Bold.ttf')); } catch (_) { cjkBold = cjk; }
  final fb = cjk != null ? [cjk] : <pw.Font>[];
  final theme = cjk != null ? pw.ThemeData.withFont(base: cjk, bold: cjkBold ?? cjk) : pw.ThemeData();

  pw.TextStyle ts(double s, {PdfColor? c, bool bold = false}) => pw.TextStyle(
      fontSize: s, color: c ?? _black, fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal, fontFallback: fb);

  pw.MemoryImage? logo;
  if (logoBase64 != null && logoBase64.isNotEmpty) {
    try { logo = pw.MemoryImage(base64Decode(logoBase64.split(',').last)); } catch (_) {}
  }

  double netOf(Map<String, String> r) {
    final qty = double.tryParse(r['qty'] ?? '1') ?? 1;
    final price = double.tryParse(r['price'] ?? '0') ?? 0;
    return qty * price;
  }
  final total = rows.fold<double>(0, (s, r) => s + netOf(r));
  String rm(double v) => 'RM ${v.toStringAsFixed(2)}';

  pw.Widget gap(double h) => pw.SizedBox(height: h);
  pw.Widget rule({double t = 0.5, PdfColor? c}) => pw.Divider(thickness: t, color: c ?? _rule, height: 1);
  pw.Widget metaRow(String l, String v, pw.TextStyle ls, pw.TextStyle vs) => pw.Padding(
    padding: const pw.EdgeInsets.only(bottom: 2),
    child: pw.Row(mainAxisAlignment: pw.MainAxisAlignment.end, children: [pw.Text('$l:  ', style: ls), pw.Text(v, style: vs)]),
  );

  final pdf = pw.Document(theme: theme);
  pdf.addPage(pw.MultiPage(
    pageFormat: PdfPageFormat.a4,
    margin: const pw.EdgeInsets.fromLTRB(52, 48, 52, 40),
    footer: (ctx) => pw.Padding(padding: const pw.EdgeInsets.only(top: 6), child: pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, children: [
        pw.Text('Generated by Bookly MY  ·  $poDate', style: ts(7, c: _light)),
        pw.Text('Page ${ctx.pageNumber} of ${ctx.pagesCount}', style: ts(7, c: _light)),
      ])),
    build: (ctx) => [
      pw.Row(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
        pw.Expanded(child: pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
          if (logo != null) ...[pw.Image(logo, height: 44, fit: pw.BoxFit.contain), gap(6)],
          pw.Text(co.companyName, style: ts(11, bold: true)),
          if (co.coReg.isNotEmpty)   pw.Text('SSM/Reg No: ${co.coReg}', style: ts(8, c: _grey)),
          if (co.coAddr.isNotEmpty)  pw.Text(co.coAddr, style: ts(8, c: _grey)),
          if (co.coPhone.isNotEmpty) pw.Text('Tel: ${co.coPhone}', style: ts(8, c: _grey)),
        ])),
        pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.end, children: [
          pw.Text('PURCHASE ORDER', style: ts(20, bold: true)),
          gap(10),
          metaRow('P.O. No', poNo,   ts(8, c: _grey), ts(8, bold: true)),
          metaRow('Date',    poDate, ts(8, c: _grey), ts(8)),
        ]),
      ]),
      gap(20), rule(t: 1.0, c: _black), gap(14),

      pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
        pw.Text('SUPPLIER', style: ts(7, c: _light, bold: true)),
        gap(4),
        pw.Text((supplier['name'] ?? '') as String, style: ts(10, bold: true)),
        if (((supplier['regNo'] ?? '') as String).isNotEmpty)
          pw.Text('Reg No: ${supplier['regNo']}', style: ts(8, c: _grey)),
        if (((supplier['address'] ?? '') as String).isNotEmpty)
          pw.Text((supplier['address']) as String, style: ts(8, c: _grey)),
        if (((supplier['phone'] ?? '') as String).isNotEmpty)
          pw.Text((supplier['phone']) as String, style: ts(8, c: _grey)),
      ]),
      gap(18), rule(t: 1.0, c: _black),

      pw.Padding(padding: const pw.EdgeInsets.symmetric(vertical: 6), child: pw.Row(children: [
        pw.SizedBox(width: 20, child: pw.Text('NO', style: ts(7.5, c: _grey, bold: true))),
        pw.Expanded(flex: 5, child: pw.Text('DESCRIPTION', style: ts(7.5, c: _grey, bold: true))),
        pw.SizedBox(width: 40, child: pw.Text('QTY', style: ts(7.5, c: _grey, bold: true), textAlign: pw.TextAlign.right)),
        pw.SizedBox(width: 70, child: pw.Text('UNIT', style: ts(7.5, c: _grey, bold: true), textAlign: pw.TextAlign.right)),
        pw.SizedBox(width: 76, child: pw.Text('AMOUNT', style: ts(7.5, c: _grey, bold: true), textAlign: pw.TextAlign.right)),
      ])),
      rule(),

      ...rows.asMap().entries.map((e) {
        final i = e.key; final r = e.value;
        final qty = double.tryParse(r['qty'] ?? '1') ?? 1;
        final price = double.tryParse(r['price'] ?? '0') ?? 0;
        return pw.Container(
          color: i.isOdd ? _alt : null,
          padding: const pw.EdgeInsets.symmetric(vertical: 5),
          child: pw.Row(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
            pw.SizedBox(width: 20, child: pw.Text('${i + 1}', style: ts(8, c: _grey))),
            pw.Expanded(flex: 5, child: pw.Text(r['desc'] ?? '', style: ts(8.5))),
            pw.SizedBox(width: 40, child: pw.Text(qty.toStringAsFixed(qty == qty.truncate() ? 0 : 2), style: ts(8.5), textAlign: pw.TextAlign.right)),
            pw.SizedBox(width: 70, child: pw.Text(rm(price), style: ts(8.5), textAlign: pw.TextAlign.right)),
            pw.SizedBox(width: 76, child: pw.Text(rm(qty * price), style: ts(8.5, bold: true), textAlign: pw.TextAlign.right)),
          ]),
        );
      }),
      rule(), gap(10),

      pw.Align(alignment: pw.Alignment.centerRight, child: pw.SizedBox(width: 200, child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, children: [
          pw.Text('TOTAL', style: ts(10, bold: true)),
          pw.Text(rm(total), style: ts(10, bold: true)),
        ]))),

      if (notes != null && notes.isNotEmpty) ...[
        gap(20), rule(), gap(8),
        pw.Text('Notes', style: ts(8, c: _grey, bold: true)), gap(4),
        pw.Text(notes, style: ts(8.5, c: _grey)),
      ],
      gap(30),
      pw.Container(width: 180, height: 0.8, color: _black),
      gap(4),
      pw.Text('Authorised Signature', style: ts(7.5, c: _grey)),
    ],
  ));
  return pdf.save();
}
