// ─── quotation_pdf.dart ────────────────────────────────────────────────────────
// Malaysia Quotation — clean black/white layout (reuses invoice_pdf structure)
// ─────────────────────────────────────────────────────────────────────────────

import 'dart:convert';
import 'dart:typed_data';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../models.dart';

const _black  = PdfColors.black;
const _grey   = PdfColor.fromInt(0xFF555555);
const _light  = PdfColor.fromInt(0xFF888888);
const _rule   = PdfColor.fromInt(0xFFBBBBBB);
const _rowAlt = PdfColor.fromInt(0xFFF7F7F7);

const _sstRate = {
  'none': 0.0, 'sst5': 0.05, 'sst10': 0.10,
  'service6': 0.06, 'service8': 0.08,
};
const _sstLabel = {
  'none': '—', 'sst5': 'Sales 5%', 'sst10': 'Sales 10%',
  'service6': 'Svc 6%', 'service8': 'Svc 8%',
};

class _TaxBucket {
  final String label;
  final double netAmt;
  final double sstAmt;
  const _TaxBucket({required this.label, required this.netAmt, required this.sstAmt});
}

Future<Uint8List> generateQuotationPdf({
  required AppSettings co,
  required Customer    customer,
  required List<Map<String, String>> rows,
  required String quotNo,
  required String quotDate,
  String? validUntil,
  String? logoBase64,
  String? notes,
}) async {

  pw.Font? cjk;
  pw.Font? cjkBold;
  try {
    final fd = await rootBundle.load('assets/fonts/NotoSansSC-Regular.ttf');
    cjk = pw.Font.ttf(fd);
  } catch (_) {}
  try {
    final fd = await rootBundle.load('assets/fonts/NotoSansSC-Bold.ttf');
    cjkBold = pw.Font.ttf(fd);
  } catch (_) { cjkBold = cjk; }

  final List<pw.Font> fb = cjk != null ? [cjk] : [];
  final pw.ThemeData theme = cjk != null
      ? pw.ThemeData.withFont(base: cjk, bold: cjkBold ?? cjk)
      : pw.ThemeData();

  pw.TextStyle ts(double sz, {PdfColor? c, bool bold = false}) => pw.TextStyle(
      fontSize: sz,
      color: c ?? _black,
      fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
      fontFallback: fb);

  pw.MemoryImage? logo;
  if (logoBase64 != null && logoBase64.isNotEmpty) {
    try { logo = pw.MemoryImage(base64Decode(logoBase64.split(',').last)); } catch (_) {}
  }

  double netOf(Map<String, String> r) {
    final qty   = double.tryParse(r['qty']   ?? '1') ?? 1;
    final price = double.tryParse(r['price'] ?? '0') ?? 0;
    final disc  = double.tryParse(r['disc']  ?? '0') ?? 0;
    return qty * price * (1 - disc / 100);
  }
  double sstOf(Map<String, String> r) =>
      netOf(r) * (_sstRate[r['sst'] ?? 'none'] ?? 0);

  final subtotal = rows.fold<double>(0, (s, r) => s + netOf(r));
  final totalSST = rows.fold<double>(0, (s, r) => s + sstOf(r));
  final grand    = subtotal + totalSST;
  final hasSst   = totalSST > 0;

  final Map<String, _TaxBucket> buckets = {};
  for (final r in rows) {
    final key = r['sst'] ?? 'none';
    if (key == 'none') continue;
    buckets[key] = _TaxBucket(
      label:  _sstLabel[key] ?? key,
      netAmt: (buckets[key]?.netAmt ?? 0) + netOf(r),
      sstAmt: (buckets[key]?.sstAmt ?? 0) + sstOf(r),
    );
  }

  String rm(double v) => 'RM ${v.toStringAsFixed(2)}';

  pw.Widget rule({double thick = 0.5, PdfColor? color}) =>
      pw.Divider(thickness: thick, color: color ?? _rule, height: 1);
  pw.Widget gap(double h) => pw.SizedBox(height: h);

  pw.Widget _metaRow(String label, String value,
      pw.TextStyle labelStyle, pw.TextStyle valueStyle) =>
    pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 2),
      child: pw.Row(mainAxisAlignment: pw.MainAxisAlignment.end, children: [
        pw.Text('$label:  ', style: labelStyle),
        pw.Text(value, style: valueStyle),
      ]),
    );

  final pdf = pw.Document(theme: theme);

  pdf.addPage(pw.MultiPage(
    pageFormat: PdfPageFormat.a4,
    margin: const pw.EdgeInsets.fromLTRB(52, 48, 52, 40),
    footer: (ctx) => pw.Container(
      padding: const pw.EdgeInsets.only(top: 6),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text('Generated by Bookly MY  ·  $quotDate', style: ts(7, c: _light)),
          pw.Text('Page ${ctx.pageNumber} of ${ctx.pagesCount}', style: ts(7, c: _light)),
        ],
      ),
    ),
    build: (ctx) => [

      // ══ HEADER ══════════════════════════════════════════════════════════
      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                if (logo != null) ...[
                  pw.Image(logo, height: 44, fit: pw.BoxFit.contain),
                  gap(6),
                ],
                pw.Text(co.companyName, style: ts(11, bold: true)),
                if (co.coReg.isNotEmpty)
                  pw.Text('SSM/Reg No: ${co.coReg}',    style: ts(8, c: _grey)),
                if (co.sstRegNo.isNotEmpty)
                  pw.Text('SST Reg No: ${co.sstRegNo}', style: ts(8, c: _grey)),
                if (co.coAddr.isNotEmpty)
                  pw.Text(co.coAddr,                    style: ts(8, c: _grey)),
                if (co.coPhone.isNotEmpty)
                  pw.Text('Tel: ${co.coPhone}',         style: ts(8, c: _grey)),
                if (co.coEmail.isNotEmpty)
                  pw.Text(co.coEmail,                   style: ts(8, c: _grey)),
              ],
            ),
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text('QUOTATION', style: ts(20, bold: true)),
              gap(10),
              _metaRow('Quotation No', quotNo,   ts(8, c: _grey), ts(8, bold: true)),
              _metaRow('Date',         quotDate, ts(8, c: _grey), ts(8)),
              if (validUntil != null && validUntil.isNotEmpty)
                _metaRow('Valid Until', validUntil, ts(8, c: _grey), ts(8, bold: true)),
            ],
          ),
        ],
      ),

      gap(20),
      rule(thick: 1.0, color: _black),
      gap(14),

      // ══ BILL TO ══════════════════════════════════════════════════════════
      pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('QUOTATION FOR', style: ts(7, c: _light, bold: true)),
          gap(4),
          pw.Text(customer.name, style: ts(10, bold: true)),
          if (customer.regNo.isNotEmpty)
            pw.Text('SSM/Reg No: ${customer.regNo}', style: ts(8, c: _grey)),
          if (customer.sstRegNo.isNotEmpty)
            pw.Text('SST: ${customer.sstRegNo}',     style: ts(8, c: _grey)),
          if (customer.address.isNotEmpty)
            pw.Text(customer.address,                style: ts(8, c: _grey)),
          if (customer.phone.isNotEmpty)
            pw.Text(customer.phone,                  style: ts(8, c: _grey)),
          if (customer.email.isNotEmpty)
            pw.Text(customer.email,                  style: ts(8, c: _grey)),
        ],
      ),

      gap(18),
      rule(thick: 1.0, color: _black),

      // ══ TABLE HEADER ══════════════════════════════════════════════════════
      pw.Padding(
        padding: const pw.EdgeInsets.symmetric(vertical: 6),
        child: pw.Row(children: [
          pw.SizedBox(width: 20,
              child: pw.Text('NO',          style: ts(7.5, c: _grey, bold: true))),
          pw.Expanded(flex: 5,
              child: pw.Text('DESCRIPTION', style: ts(7.5, c: _grey, bold: true))),
          pw.SizedBox(width: 36,
              child: pw.Text('QTY',         style: ts(7.5, c: _grey, bold: true),
                  textAlign: pw.TextAlign.right)),
          pw.SizedBox(width: 68,
              child: pw.Text('UNIT PRICE',  style: ts(7.5, c: _grey, bold: true),
                  textAlign: pw.TextAlign.right)),
          if (hasSst)
            pw.SizedBox(width: 52,
                child: pw.Text('TAX',       style: ts(7.5, c: _grey, bold: true),
                    textAlign: pw.TextAlign.right)),
          pw.SizedBox(width: 72,
              child: pw.Text('AMOUNT',      style: ts(7.5, c: _grey, bold: true),
                  textAlign: pw.TextAlign.right)),
        ]),
      ),
      rule(),

      // ══ TABLE ROWS ════════════════════════════════════════════════════════
      ...rows.asMap().entries.map((entry) {
        final i = entry.key;
        final r = entry.value;
        final qty   = double.tryParse(r['qty']   ?? '1') ?? 1;
        final price = double.tryParse(r['price'] ?? '0') ?? 0;
        final disc  = double.tryParse(r['disc']  ?? '0') ?? 0;
        final net   = netOf(r);
        final sst   = sstOf(r);
        final sstKey = r['sst'] ?? 'none';

        return pw.Container(
          color: i.isOdd ? _rowAlt : null,
          padding: const pw.EdgeInsets.symmetric(horizontal: 0, vertical: 5),
          child: pw.Row(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
            pw.SizedBox(width: 20,
                child: pw.Text('${i + 1}', style: ts(8, c: _grey))),
            pw.Expanded(flex: 5, child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
              pw.Text(r['desc'] ?? '', style: ts(8.5)),
              if ((r['note'] ?? '').isNotEmpty)
                pw.Text(r['note']!, style: ts(7, c: _grey)),
              if (disc > 0)
                pw.Text('Disc ${disc.toStringAsFixed(0)}%', style: ts(7, c: _grey)),
            ])),
            pw.SizedBox(width: 36,
                child: pw.Text(qty.toStringAsFixed(qty == qty.truncate() ? 0 : 2),
                    style: ts(8.5), textAlign: pw.TextAlign.right)),
            pw.SizedBox(width: 68,
                child: pw.Text(rm(price), style: ts(8.5),
                    textAlign: pw.TextAlign.right)),
            if (hasSst)
              pw.SizedBox(width: 52,
                  child: pw.Text(sstKey != 'none' ? (_sstLabel[sstKey] ?? '—') : '—',
                      style: ts(7.5, c: _grey), textAlign: pw.TextAlign.right)),
            pw.SizedBox(width: 72,
                child: pw.Text(rm(net + sst), style: ts(8.5, bold: true),
                    textAlign: pw.TextAlign.right)),
          ]),
        );
      }),

      rule(),
      gap(10),

      // ══ TOTALS ════════════════════════════════════════════════════════════
      pw.Align(
        alignment: pw.Alignment.centerRight,
        child: pw.SizedBox(
          width: 200,
          child: pw.Column(children: [
            pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, children: [
              pw.Text('Subtotal', style: ts(8.5, c: _grey)),
              pw.Text(rm(subtotal), style: ts(8.5)),
            ]),
            if (hasSst) ...[
              gap(4),
              ...buckets.values.map((b) => pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, children: [
                  pw.Text(b.label, style: ts(8.5, c: _grey)),
                  pw.Text(rm(b.sstAmt), style: ts(8.5)),
                ],
              )),
            ],
            gap(6),
            rule(thick: 0.8, color: _black),
            gap(4),
            pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, children: [
              pw.Text('TOTAL', style: ts(10, bold: true)),
              pw.Text(rm(grand), style: ts(10, bold: true)),
            ]),
          ]),
        ),
      ),

      gap(24),

      // ══ NOTES ════════════════════════════════════════════════════════════
      if (notes != null && notes.isNotEmpty) ...[
        rule(),
        gap(10),
        pw.Text('Notes', style: ts(8, c: _grey, bold: true)),
        gap(4),
        pw.Text(notes, style: ts(8.5, c: _grey)),
        gap(16),
      ],

      // ══ FOOTER ════════════════════════════════════════════════════════════
      gap(20),
      rule(),
      gap(8),
      pw.Text(
        'This is a quotation only and is not a tax invoice. '
        'Prices are subject to change without prior notice.',
        style: ts(7, c: _light),
      ),
    ],
  ));

  return pdf.save();
}
